name: Build
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update kernel
        run: sudo apt-get update && sudo apt-get install -y
      - name: Download dependencies
        run: sudo apt install nodejs npm
      - name: Build
        run: |
          npm i
          npm run build
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update kernel
        run: sudo apt-get update && sudo apt-get install -y
      - name: Download dependencies
        run: sudo apt install nodejs npm
      - name: Build
        run: |
          npm i
          npm run build
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Generate tag (timestamp-based)
        id: tagger
        run: |
          TAG="auto-$(date +%Y%m%d%H%M%S)"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          git tag $TAG
          git push origin $TAG
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tagger.outputs.tag }}
          name: Release ${{ steps.tagger.outputs.tag }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
