name: Build
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update kernel
        run: sudo apt-get update && sudo apt-get install -y
      - name: Download dependencies
        run: sudo apt install nodejs npm
      - name: Build
        run: |
          npm i
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled data
          path: dist/
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 1
          path: .
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with: 
          name: compiled data
          path: dist/
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Generate tag (timestamp-based)
        id: tagger
        run: |
          TAG="auto-$(date +%Y%m%d%H%M%S)"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          git tag $TAG
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git push origin $TAG
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tagger.outputs.tag }}
          name: Release ${{ steps.tagger.outputs.tag }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 1
          path: .
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with: 
          name: compiled data
          path: dist/
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: push
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./dist
          publish_branch: dist
          force_orphan: true